apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-test-deployment
spec:
  selector:
    matchLabels:
      app: crud-test-pod
  template:
    metadata:
      labels:
        app: crud-test-pod
    spec:
      containers:
      - name: crud-test-container
        image: jacielgzz.azurecr.io/crud-test:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
